name: Build Executable

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Check out repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pyinstaller PyQt5

      - name: Build executable
        run: |
          pyinstaller --onefile env_var_editor.py

      - name: Upload executable
        uses: actions/upload-artifact@v4
        with:
          name: env_var_editor_exe
          path: dist

      - name: Show download link
        run: echo "Download the executable at https://github.com/${{ github.repository }}/actions/runs/${{ github.run_id }}#artifacts"
